FROM centos:latest
MAINTAINER Zachi Sharvit
RUN yum install -y java-1.8.0-openjdk-devel.x86_64
RUN yum -y install tomcat
RUN echo "JAVA_HOME=/usr/lib/jvm/java" >> /etc/default/tomcat
RUN mkdir /logs
ENV NAME name
ENTRYPOINT tomcat start && tail -F /logs/catalina.out
ADD {{war_url}}  /usr/share/tomcat/webapps


